// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user": amazon Resource Client
//
// Command:
// $ goagen
// --design=gigglesearch.org/giggle-auth/auth/design
// --out=$(GOPATH)/src/gigglesearch.org/giggle-auth/auth
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// AttachToAccountAmazonPath computes a request path to the attach-to-account action of amazon.
func AttachToAccountAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/attach")
}

// Attaches a Amazon account to an existing user account, returns the URL the browser should be redirected to
func (c *Client) AttachToAccountAmazon(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAttachToAccountAmazonRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAttachToAccountAmazonRequest create the request corresponding to the attach-to-account action endpoint of the amazon resource.
func (c *Client) NewAttachToAccountAmazonRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// DetachFromAccountAmazonPath computes a request path to the detach-from-account action of amazon.
func DetachFromAccountAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/detach")
}

// Detaches a Amazon account from an existing user account.
func (c *Client) DetachFromAccountAmazon(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDetachFromAccountAmazonRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDetachFromAccountAmazonRequest create the request corresponding to the detach-from-account action endpoint of the amazon resource.
func (c *Client) NewDetachFromAccountAmazonRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// LoginAmazonPath computes a request path to the login action of amazon.
func LoginAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/login")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Amazon, to be logged in
func (c *Client) LoginAmazon(ctx context.Context, path string, token *uuid.UUID) (*http.Response, error) {
	req, err := c.NewLoginAmazonRequest(ctx, path, token)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewLoginAmazonRequest create the request corresponding to the login action endpoint of the amazon resource.
func (c *Client) NewLoginAmazonRequest(ctx context.Context, path string, token *uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if token != nil {
		tmp88 := token.String()
		values.Set("token", tmp88)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ReceiveAmazonPath computes a request path to the receive action of amazon.
func ReceiveAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/receive")
}

// The endpoint that Amazon redirects the browser to after the user has authenticated
func (c *Client) ReceiveAmazon(ctx context.Context, path string, code string, state uuid.UUID) (*http.Response, error) {
	req, err := c.NewReceiveAmazonRequest(ctx, path, code, state)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewReceiveAmazonRequest create the request corresponding to the receive action endpoint of the amazon resource.
func (c *Client) NewReceiveAmazonRequest(ctx context.Context, path string, code string, state uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("code", code)
	tmp89 := state.String()
	values.Set("state", tmp89)
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterAmazonPath computes a request path to the register action of amazon.
func RegisterAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/register")
}

// Registers a new account with the system, with Amazon as the login system
func (c *Client) RegisterAmazon(ctx context.Context, path string, payload *AmazonRegisterParams, contentType string) (*http.Response, error) {
	req, err := c.NewRegisterAmazonRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterAmazonRequest create the request corresponding to the register action endpoint of the amazon resource.
func (c *Client) NewRegisterAmazonRequest(ctx context.Context, path string, payload *AmazonRegisterParams, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterURLAmazonPath computes a request path to the register-url action of amazon.
func RegisterURLAmazonPath() string {

	return fmt.Sprintf("/api/v1/user/auth/amazon/register-start")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Amazon, and then register
func (c *Client) RegisterURLAmazon(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRegisterURLAmazonRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterURLAmazonRequest create the request corresponding to the register-url action endpoint of the amazon resource.
func (c *Client) NewRegisterURLAmazonRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
