// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user": facebook Resource Client
//
// Command:
// $ goagen
// --design=gigglesearch.org/giggle-auth/auth/design
// --out=$(GOPATH)/src/gigglesearch.org/giggle-auth/auth
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// AttachToAccountFacebookPath computes a request path to the attach-to-account action of facebook.
func AttachToAccountFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/attach")
}

// Attaches a Facebook account to an existing user account, returns the URL the browser should be redirected to
func (c *Client) AttachToAccountFacebook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAttachToAccountFacebookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAttachToAccountFacebookRequest create the request corresponding to the attach-to-account action endpoint of the facebook resource.
func (c *Client) NewAttachToAccountFacebookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// DetachFromAccountFacebookPath computes a request path to the detach-from-account action of facebook.
func DetachFromAccountFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/detach")
}

// Detaches a Facebook account from an existing user account.
func (c *Client) DetachFromAccountFacebook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDetachFromAccountFacebookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDetachFromAccountFacebookRequest create the request corresponding to the detach-from-account action endpoint of the facebook resource.
func (c *Client) NewDetachFromAccountFacebookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// LoginFacebookPath computes a request path to the login action of facebook.
func LoginFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/login")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Facebook, to be logged in
func (c *Client) LoginFacebook(ctx context.Context, path string, token *uuid.UUID) (*http.Response, error) {
	req, err := c.NewLoginFacebookRequest(ctx, path, token)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewLoginFacebookRequest create the request corresponding to the login action endpoint of the facebook resource.
func (c *Client) NewLoginFacebookRequest(ctx context.Context, path string, token *uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if token != nil {
		tmp90 := token.String()
		values.Set("token", tmp90)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ReceiveFacebookPath computes a request path to the receive action of facebook.
func ReceiveFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/receive")
}

// The endpoint that Facebook redirects the browser to after the user has authenticated
func (c *Client) ReceiveFacebook(ctx context.Context, path string, code string, state uuid.UUID) (*http.Response, error) {
	req, err := c.NewReceiveFacebookRequest(ctx, path, code, state)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewReceiveFacebookRequest create the request corresponding to the receive action endpoint of the facebook resource.
func (c *Client) NewReceiveFacebookRequest(ctx context.Context, path string, code string, state uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("code", code)
	tmp91 := state.String()
	values.Set("state", tmp91)
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterFacebookPath computes a request path to the register action of facebook.
func RegisterFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/register")
}

// Registers a new account with the system, with Facebook as the login system
func (c *Client) RegisterFacebook(ctx context.Context, path string, payload *FacebookRegisterParams, contentType string) (*http.Response, error) {
	req, err := c.NewRegisterFacebookRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterFacebookRequest create the request corresponding to the register action endpoint of the facebook resource.
func (c *Client) NewRegisterFacebookRequest(ctx context.Context, path string, payload *FacebookRegisterParams, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterURLFacebookPath computes a request path to the register-url action of facebook.
func RegisterURLFacebookPath() string {

	return fmt.Sprintf("/api/v1/user/auth/facebook/register-start")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Facebook, and then register
func (c *Client) RegisterURLFacebook(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRegisterURLFacebookRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterURLFacebookRequest create the request corresponding to the register-url action endpoint of the facebook resource.
func (c *Client) NewRegisterURLFacebookRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
