// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user": linkedin Resource Client
//
// Command:
// $ goagen
// --design=gigglesearch.org/giggle-auth/auth/design
// --out=$(GOPATH)/src/gigglesearch.org/giggle-auth/auth
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	uuid "github.com/goadesign/goa/uuid"
	"net/http"
	"net/url"
)

// AttachToAccountLinkedinPath computes a request path to the attach-to-account action of linkedin.
func AttachToAccountLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/attach")
}

// Attaches a Linkedin account to an existing user account, returns the URL the browser should be redirected to
func (c *Client) AttachToAccountLinkedin(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAttachToAccountLinkedinRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAttachToAccountLinkedinRequest create the request corresponding to the attach-to-account action endpoint of the linkedin resource.
func (c *Client) NewAttachToAccountLinkedinRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// DetachFromAccountLinkedinPath computes a request path to the detach-from-account action of linkedin.
func DetachFromAccountLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/detach")
}

// Detaches a Linkedin account from an existing user account.
func (c *Client) DetachFromAccountLinkedin(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDetachFromAccountLinkedinRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDetachFromAccountLinkedinRequest create the request corresponding to the detach-from-account action endpoint of the linkedin resource.
func (c *Client) NewDetachFromAccountLinkedinRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// LoginLinkedinPath computes a request path to the login action of linkedin.
func LoginLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/login")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Linkedin, to be logged in
func (c *Client) LoginLinkedin(ctx context.Context, path string, token *uuid.UUID) (*http.Response, error) {
	req, err := c.NewLoginLinkedinRequest(ctx, path, token)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewLoginLinkedinRequest create the request corresponding to the login action endpoint of the linkedin resource.
func (c *Client) NewLoginLinkedinRequest(ctx context.Context, path string, token *uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if token != nil {
		tmp94 := token.String()
		values.Set("token", tmp94)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ReceiveLinkedinPath computes a request path to the receive action of linkedin.
func ReceiveLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/receive")
}

// The endpoint that Linkedin redirects the browser to after the user has authenticated
func (c *Client) ReceiveLinkedin(ctx context.Context, path string, code string, state uuid.UUID) (*http.Response, error) {
	req, err := c.NewReceiveLinkedinRequest(ctx, path, code, state)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewReceiveLinkedinRequest create the request corresponding to the receive action endpoint of the linkedin resource.
func (c *Client) NewReceiveLinkedinRequest(ctx context.Context, path string, code string, state uuid.UUID) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("code", code)
	tmp95 := state.String()
	values.Set("state", tmp95)
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterLinkedinPath computes a request path to the register action of linkedin.
func RegisterLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/register")
}

// Registers a new account with the system, with Linkedin as the login system
func (c *Client) RegisterLinkedin(ctx context.Context, path string, payload *LinkedinRegisterParams, contentType string) (*http.Response, error) {
	req, err := c.NewRegisterLinkedinRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterLinkedinRequest create the request corresponding to the register action endpoint of the linkedin resource.
func (c *Client) NewRegisterLinkedinRequest(ctx context.Context, path string, payload *LinkedinRegisterParams, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// RegisterURLLinkedinPath computes a request path to the register-url action of linkedin.
func RegisterURLLinkedinPath() string {

	return fmt.Sprintf("/api/v1/user/auth/linkedin/register-start")
}

// Gets the URL the front-end should redirect the browser to in order to be authenticated with Linkedin, and then register
func (c *Client) RegisterURLLinkedin(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRegisterURLLinkedinRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRegisterURLLinkedinRequest create the request corresponding to the register-url action endpoint of the linkedin resource.
func (c *Client) NewRegisterURLLinkedinRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.KeySigner != nil {
		if err := c.KeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
